version: "3.9"
services:
  web:
    environment:
      - TORCH_HOME=/models
      - REDIS_HOST=redis
    volumes:
      - ./models:/models
    build: 
      context: ./
      dockerfile: ./Dockerfile_Web
    ports:
      - "5000:5000"
  
  inference:
    environment:
      - TORCH_HOME=/models
      - REDIS_HOST=redis
    volumes:
      - ./models:/models
    build: 
      context: ./
      dockerfile: ./Dockerfile_Inference

  redis:
    image: "redis:alpine"